{ config, pkgs, lib, atlasUser, atlasHome, ... }:

let
  atlasPath = "${config.home.homeDirectory}/.local/share/atlas";
  dotfiles = "${atlasPath}/config";

  createSymlink = path:
    config.lib.file.mkOutOfStoreSymlink path;

  configs = {
    btop = "btop";
    fastfetch = "fastfetch";
    kitty = "kitty";
    nvim = "nvim";
    quickshell = "quickshell";
    tmux = "tmux";
    zathura = "zathura";
  };
in
{
  home.username = atlasUser;
  home.homeDirectory = atlasHome;
  home.stateVersion = "26.05";

  imports = [
    ./modules/theme.nix
  ];

  home.packages = with pkgs; [
    cava
    kitty
    neovim
    quickshell
    tree-sitter
    tmux
    zathura

    (pkgs.writeShellApplication {
      name = "ns";

      runtimeInputs = with pkgs; [
        fzf
        nix-search-tv
      ];

      text = builtins.readFile "${pkgs.nix-search-tv.src}/nixpkgs.sh";
    })
  ];

  home.sessionVariables = {
    ATLAS_PATH = atlasPath;
  };

  home.sessionPath = [
    "${atlasPath}/bin"
  ];

  programs.bash = {
    enable = true;

    initExtra = ''
      fastfetch
    '';

    shellAliases = {
      nrs = "sudo env ATLAS_USER=${atlasUser} ATLAS_HOME=${atlasHome} nixos-rebuild switch --impure --flake ${atlasPath}#atlas";
    };
  };

  programs.starship = {
    enable = true;
    enableBashIntegration = true;
  };

  xdg.configFile =
    (builtins.mapAttrs
      (_: subpath: {
        source = createSymlink "${dotfiles}/${subpath}";
      })
      configs)
    // {
      "starship.toml".source =
        createSymlink "${dotfiles}/starship/starship.toml";
    };

  home.activation.installHyprConfig =
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      source_dir="${dotfiles}/hypr"
      target_dir="${config.home.homeDirectory}/.config/hypr"
      target_config="$target_dir/hyprland.lua"

      skip_install=false

      if [ -L "$target_dir" ]; then
        symlink_target="$(${pkgs.coreutils}/bin/readlink -f "$target_dir")"
        atlas_target="$(${pkgs.coreutils}/bin/readlink -f "$source_dir")"

        if [ "$symlink_target" = "$atlas_target" ]; then
          echo "Atlas: migrating Hyprland configuration from managed symlink."

          $DRY_RUN_CMD \
            ${pkgs.coreutils}/bin/rm "$target_dir"
        else
          echo "Atlas: ~/.config/hypr is a user-managed symlink."
          echo "Atlas: leaving Hyprland configuration untouched."

          skip_install=true
        fi
      fi

      if [ "$skip_install" = false ]; then

        $DRY_RUN_CMD \
          ${pkgs.coreutils}/bin/mkdir -p "$target_dir"

        if [ -f "$target_config" ]; then
          if ${pkgs.gnugrep}/bin/grep -Fq \
            'hl.config({ autogenerated = true })' \
            "$target_config"; then

            echo "Atlas: replacing autogenerated hyprland.lua."

            $DRY_RUN_CMD \
              ${pkgs.coreutils}/bin/rm "$target_config"
          fi
        fi

        $DRY_RUN_CMD \
          ${pkgs.rsync}/bin/rsync \
            -a \
            --ignore-existing \
            "$source_dir/" \
            "$target_dir/"
      fi
    '';
}
