wallpaper {
    monitor =
    # path = ~/Pictures/wallpapers/Simple/city.jpg
    # Correct path when themes are used
    path = ~/.config/style/current/background
    fit_mode = cover
}

splash = false
