global terminal = "kitty"
global fileManager = "kitty yazi"
global notes = "obsidian"
global notesWindow = "class:^(obsidian)$"
-- global browser = "brave-origin"
-- global browserWindow = "class:^(brave-origin)$"
global browser = "brave"
global browserWindow = "class:^(brave-browser)$"
global music = "spotify"
global musicWindow = "class:^(Spotify)$"
global musicWorkspace = 1
global browserWorkspace = 2
global notesWorkspace = 4
global cliamp = "kitty --class cliamp cliamp"
global cliampWindow = "class:^(cliamp)$"
global btop = "kitty --class btop btop"
global btopWindow = "class:^(btop)$"
