include ~/.config/style/current/kitty.conf

# Follow palette changes made by theme-set/theme-refresh.
auto_reload_config 0.1

# Font
font_family      FiraCode Nerd Font Mono
bold_italic_font auto
font_size        9.0

# Window
window_padding_width 6
hide_window_decorations yes
confirm_os_window_close 0
background_opacity 0.9

# Aesthetics
shell_integration no-cursor
enable_audio_bell no
